export const CREATE_SCOOTERS_LIST = "CREATE_SCOOTERS_LIST";
export const GET_SCOOTERS_LIST = "GET_SCOOTERS_LIST";
export const DELETE_SCOOTERS_LIST = "DELETE_SCOOTERS_LIST";
export const EDIT_SCOOTERS_LIST = "EDIT_SCOOTERS_LIST";
